### ISSUE TITLE
Erro ao conversar com NPCs 

### ISSUE THREAD

**Issue by hmarcuzzo** [YaanLiima/3996#1]
Olá @YaanLiima , gostaria de reportar um bug, provavelmente na função _getDistanceTo_ ou _onCreatureSay_, pois quando converso com um NPC no servidor o seguinte erro é retornado:

`[Error - NpcScript Interface]                                                 
data/npc/scripts/default.lua:onCreatureSay 
Description:                                                                             
data/npc/lib/npcsystem/npchandler.lua:558: attempt to call global 'getDistanceTo' (a nil value)           stack traceback:                                                                                       
    data/npc/lib/npcsystem/npchandler.lua:558: in function 'isInRange'                             
    data/npc/lib/npcsystem/npchandler.lua:381: in function 'onCreatureSay'                               
    data/npc/scripts/default.lua:7: in function <data/npc/scripts/default.lua:7>`

**Comment by YaanLiima** [comment]
> Olá @YaanLiima , gostaria de reportar um bug, provavelmente na função _getDistanceTo_ ou _onCreatureSay_, pois quando converso com um NPC no servidor o seguinte erro é retornado:
> 
> `[Error - NpcScript Interface] data/npc/scripts/default.lua:onCreatureSay Description: data/npc/lib/npcsystem/npchandler.lua:558: attempt to call global 'getDistanceTo' (a nil value) stack traceback: data/npc/lib/npcsystem/npchandler.lua:558: in function 'isInRange' data/npc/lib/npcsystem/npchandler.lua:381: in function 'onCreatureSay' data/npc/scripts/default.lua:7: in function <data/npc/scripts/default.lua:7>`

Desculpe pela demora, não tinha recebido a notificação. Fiz uma alteração, poderia testar para mim fazendo um grande favor?
https://github.com/YaanLiima/3996/commit/15f1c98f55111e0aab170c83b015e4aba137f259
